### ISSUE TITLE
When will v2.10 be released to maven?

### ISSUE THREAD

**Issue by logicbomb** [giabao/playframework-standalone#1]
I'm looking forward to using HikariCP

**Comment by giabao** [comment]
Sorry for late reply.
We always release to maven before adding changelog to README.md & tagging to git repo.
(and every release versions will be used in our production server at http://sandinh.com right after that).
v2.1.0 is publish to maven [on 16-Nov-2014](http://search.maven.org/#search|gav|1|g%3A%22com.sandinh%22%20AND%20a%3A%22play-jdbc-standalone_2.11%22) (3-day before the time this issue is created)
